# Generated by Django 3.2.1 on 2021-05-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('organisation_info', models.TextField()),
                ('cause_description', models.TextField()),
                ('image', models.ImageField(default='cause_pics/hands-love.png', upload_to='cause_pics')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
