# Generated by Django 3.2.1 on 2021-05-05 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 19, 3, 0, 66286)),
        ),
    ]
