# Generated by Django 3.2 on 2021-05-04 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0002_rename_post_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cause',
            name='description',
            field=models.TextField(default='test description'),
            preserve_default=False,
        ),
    ]
