# Generated by Django 3.1.7 on 2021-05-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0004_cause_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
