# Generated by Django 3.1.7 on 2021-05-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0005_auto_20210504_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cause',
            old_name='description',
            new_name='about',
        ),
        migrations.AddField(
            model_name='cause',
            name='what_we_do',
            field=models.TextField(default='test what we do'),
            preserve_default=False,
        ),
    ]
