# Generated by Django 3.1.7 on 2021-05-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0006_auto_20210504_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cause',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='cause',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cause',
            name='image',
            field=models.ImageField(default='./cause_pics/default.jpg', upload_to='cause_pics'),
        ),
    ]
