# Generated by Django 3.1.7 on 2021-05-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0009_auto_20210504_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=models.ImageField(default='../media/cause_pics/hands-money.png', upload_to='../media/cause_pics/'),
        ),
    ]
