# Generated by Django 3.1.7 on 2021-05-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0011_auto_20210504_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cause',
            old_name='what_we_do',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='founder',
        ),
    ]
