# Generated by Django 3.1.7 on 2021-05-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0014_auto_20210505_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=models.ImageField(default='cause_pics/hands-money.png', upload_to='cause_pics'),
        ),
    ]
