# Generated by Django 3.1.7 on 2021-05-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0015_auto_20210505_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=models.ImageField(default='cause_pics/hands-love.png', upload_to='cause_pics'),
        ),
    ]
