# Generated by Django 3.1.7 on 2021-05-05 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('causes', '0016_auto_20210505_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='founder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
